spring.application.name=ScanNServe

# -------------------------
# Server
# -------------------------
server.port=${PORT:8080}
server.tomcat.max-http-form-post-size=10MB

# -------------------------
# Database
# -------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------
# JPA / Hibernate
# -------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# -------------------------
# Logging
# -------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# -------------------------
# Spring Security
# -------------------------
spring.security.user.name=superadmin
spring.security.user.password=1234

# -------------------------
# Custom Properties
# -------------------------
app.cookie.secure=false
