spring.application.name=ScanNServe
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=263136
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name = superadmin
spring.security.user.password = 1234