spring.application.name=ScanNServe
spring.datasource.url=jdbc:postgresql://localhost:5432/scan_n_serve?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=superadmin
spring.security.user.password=1234
spring.data.redis.host=localhost
spring.data.redis.port=6379
app.cookie.secure=false